AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  ApiGatewayApiCallee:
    Type: AWS::Serverless::Api
    Properties:
      StageName: testing
  ApiGatewayApiCaller:
    Type: AWS::Serverless::Api
    Properties:
      StageName: testing
  DTCalleeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DTCalleeFunction
      Handler: com.example.DTCalleeFunction::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        CalleeApi:
          Type: Api
          Properties:
            Path: /dt-callee
            Method: get
            RestApiId:
              Ref: ApiGatewayApiCallee
  DTCallerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DTCallerFunction
      Handler: com.example.DTCallerFunction::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          API_GATEWAY_PROXY_URL: !Sub https://${ApiGatewayApiCallee}.execute-api.${AWS::Region}.amazonaws.com/testing/dt-callee
      Events:
        CallerApi:
          Type: Api
          Properties:
            Path: /dt-caller
            Method: get
            RestApiId:
              Ref: ApiGatewayApiCaller
Outputs:
  CallerEndpoint:
    Description: "New Relic DT example testing stage caller endpoint"
    Value: !Sub https://${ApiGatewayApiCaller}.execute-api.${AWS::Region}.amazonaws.com/testing/dt-caller
